### PR TITLE
Incorrect match result

### PR DESCRIPTION
**Pull request by vkdltjs**

### CODE REVIEW

**Comment by geraldb** [comment]
Sorry - since you are a first time contributor and you github profile @ <https://github.com/vkdltjs> has no history and uses an encrypted pseudo-name - Can you please, explain how you have double checked the results?   Why delete the match

    Manchester United       0-2 Manchester City

is listed twice or something (due to rescheduling)?   Anyways, your contributions more than welcome.

**Comment by vkdltjs** [comment]
First I noticed that there are 2 search results for ```Manchester United       0-2 Manchester City``` (Ctrl+F) in your file.
Second https://en.wikipedia.org/wiki/2018%E2%80%9319_Manchester_City_F.C._season#Fixtures shows that there was no match between Manchester City and Manchester United on Mar 16. It was Apr 24.
Even though in the file it says
```
## in addition matchday 31
[Wed Apr/24]
  Manchester United       0-2 Manchester City
```
```sportdb build``` counts it twice.

**Comment by vkdltjs** [comment]
https://github.com/vkdltjs/england/blob/master/2017-18/1-premierleague-ii.txt
This file has the same problem.
```## in addition matchday 31```
As I said, ```sportdb build``` counts it twice.
I recommend you delete the duplicated match result in case of ```## in addition matchday XX```

**Comment by geraldb** [comment]
Thanks for the your answer. You are correct.  There are still some errors with rescheduled matches - I'm also trying to double-check with a new script - the result is in .build/conf.txt for all datasets  -> <https://github.com/openfootball/england/blob/master/.build/conf.txt#L1641>  All clubs should only have 38 entries (for the rounds).   Instead of deleting in the future, please comment out the match  with a leading `#`   - not sure yet how to best track rescheduled matches (and somehow also keep track of the old date).  Anyways, if you find any more mistake, please patch up. Keep it up. Cheers. Prosit 2020!

**Pull request merged**
